DATASET:
    nusc_version: "v1.0-trainval"
    split: "val"
    dataroot: "/data/nuscenes"
    lidar_det_path: "/data/track_result_bboxth-0.0/detection_result.json"
    # lidar_det_path: "/data/detection_result.json"
    lidar_pc_path: None
    radar_pc_path: "/data/radar_PC/radar_PC_13Hz_with_vcomp.json"
    frames_meta_path: "/data/meta_data(gt_w_vel)/frames_meta.json"
    groundTruth_path: "/data/meta_data(gt_w_vel)/annotations.json"

EVALUATE:
    dataroot: "/data/small_data2"
    eval_set: "val"
    out_dir: None
    res_path: None
    # dist_th_tp: 2.0    # Default with 2
    # custom_range: 
    #     bicycle: 40
    #     motorcycle: 40
    #     pedestrian: 40
    #     bus: 50
    #     car: 50
    #     trailer: 50
    #     truck: 50
    dist_th_tp: 3.0
    custom_range: 
        bicycle: 100
        motorcycle: 100
        pedestrian: 100
        bus: 100
        car: 100
        trailer: 100
        truck: 100

DETECTION: 
    bbox_score: 0.01
    use_nms: True
    nms_th: 0.08

SEGMENTOR:
    detCategories:
        # - 'bicycle'
        - 'bus'
        - 'car'
        # - 'motorcycle'
        - 'trailer'
        - 'truck'
        # - 'pedestrian'
    detection_th: 0.0
    dist_th: 0.0
    expand_ratio: [1.2, 1.2]    # w, l
    fuse_velocity: True
    
LIDAR_TRACKER:
    tracker: 'KF' # KF / PointTracker
    hungarian: False
    max_age: 6
    min_hits: 1
    active_th: 1.0
    update_function: 'multiplication'
    score_decay: 0.15
    detection_th: 0.025
    deletion_th: 0.0
    use_vel: True

RADAR_TRACKER:
    tracker: 'KF' # KF / PointTracker
    hungarian: False
    max_age: 6
    min_hits: 1
    active_th: 1.0
    update_function: None
    score_decay: 0.0
    detection_th: 0.0
    deletion_th: 0.0
    use_vel: False

FUSION:
    hungarian: False
    decay1: 0.0
    decay2: 0.0
    star: True
    del_th: 0.0
    min_hits: 1
    v_min: 0.4
    v_max: 1.9
    v_weight: 0.8

VISUALIZER:
    viz_cat:
        - 'bicycle'
        - 'bus'
        - 'car'
        - 'motorcycle'
        - 'trailer'
        - 'truck'
        - 'pedestrian'
        - 'background'
    range_: [200, 200]
    screenSize: [1920, 1080]
    windowSize: [920, 1000]
    imgSize: [1600, 1600]
    duration: 0.1
    background_color: [50, 50, 50]
    grid: True
    frameRate: 2 # Important for visualization (for velocity)
    radarPts:
        draw_vel: False
    radarSeg:
        colorID: True
        colorName: False
        contours: False
        draw_vel: False
    detBox:
        draw: False
        score_th: 0.01
        colorName: False
        BGRcolor: [255, 150, 150]
        draw_vel: True
    trkBox:
        colorName: False
        colorID: False
        BGRcolor: [52, 171, 235]
        draw_name: False
        draw_vel: True
        draw_id: False
    radarTrkBox:
        colorName: True
        colorID: False
        BGRcolor: [0, 255, 0]
        draw_name: False
        draw_vel: True
        draw_id: False
        draw_score: False
    fusionBox:
        colorName: True
        colorID: False
        BGRcolor: [198, 235, 52]
        draw_vel: True
        draw_id: False
        legend: True
    groundTruth:
        colorName: False
        colorID: False
        BGRcolor: [50, 50, 240]
        draw_vel: False
        draw_id: False
        thickness: -1   # Filled
        alpha: 0.5