DATASET:
    nusc_version: "v1.0-trainval"
    split: "val"
    dataroot: "/data/nuscenes"
    lidar_det_path: "/data/track_result_bboxth-0.0/detection_result.json"
    radar_pc_path: "/data/radar_PC/radar_PC_13Hz_with_vcomp.json"
    frames_meta_path: "/data/meta_data/frames_meta.json"

EVALUATE:
    dataroot: "/data/small_data2"
    out_dir: ${OUT_DIR}
    range: "default"
    tp_dist: "default"

DETECTION: 
    bbox_score: 0.01
    use_nms: False
    nms_th: 0.5

SEGMENTOR:
    detCategories:
        - 'bicycle'
        - 'bus'
        - 'car'
        - 'motorcycle'
        - 'trailer'
        - 'truck'
        # - 'pedestrian'
    expand_ratio: 1.2
    
LIDAR_TRACKER:
    tracker: 'PointTracker' # KF / PointTracker
    hungarian: False
    max_age: 6
    min_hits: 1
    active_th: 1.0
    update_function: 'multiplication'
    score_decay: 0.15
    detection_th: 0.025
    deletion_th: 0.0
    use_vel: True

RADAR_TRACKER:
    tracker: 'KF' # KF / PointTracker
    hungarian: False
    max_age: 6
    min_hits: 1
    active_th: 1.0
    update_function: None
    score_decay: 0.0
    detection_th: 0.0
    deletion_th: 0.0
    use_vel: False

FUSION:
    hungarian: False
    decay1: 0.0
    decay2: 0.0
    star: True
    del_th: 0.0
    min_hits: 1
    v_min: 0.4
    v_max: 1.9
    v_weight: 0.8

VISUALIZER:
    vizCategories:
        - 'bicycle'
        - 'bus'
        - 'car'
        - 'motorcycle'
        - 'trailer'
        - 'truck'
        - 'pedestrian'
    range: [160, 160]
    windowSize: [1000, 1000]
    imgSize: [1600, 1600]
    duration: 0.1
    grid: True
    radarSeg:
        colorID: True
        colorName: False
        contours: False
    detBox:
        colorName: False
        BGRcolor: [255, 150, 150]
        draw_vel: True
    trkBox:
        colorName: False
        colorID: False
        BGRcolor: [52, 171, 235]
        draw_vel: True
    radarTrkBox:
        colorName: False
        colorID: False
        BGRcolor: [0, 255, 0]
        draw_vel: True
    fusionBox:
        colorName: False
        colorID: True
        BGRcolor: [198, 235, 52]
        draw_vel: True